spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:tcp://localhost/~/carrot
    username: sa
    password:

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true

aws-property:
  s3-bucket-name: nowsoptbucket
  access-key: AKIAQ3EGRITRGKAVXZ4S
  secret-key: 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
  aws-region: us-east-1
